ClassStrategyCO = {};
ClassStrategyNC = {};

function InitializeStrategy()
	ClassStrategyCO = {
		[1] = {"grind","Autonomous Activity","Bot searches for targets within sight and attacks when no target in combat."},
		[2] = {"attack weak","Free Attack","Bot freely selects targets to attack in combat."},
		[3] = {"attack force","Passive Attack","Bot does not select targets in combat, requires manual target assignment."},
		[4] = {"tank","Single Target Tank","Bot only holds one target at a time, moves to next after current is defeated."},
		[5] = {"tank aoe","Multi Target Tank","Bot holds all enemies in combat as targets."},
		[6] = {"tank assist","Tank Assist","Bot assists in attacking the tank's current target in the party."},
		[7] = {"dps","Single Target DPS","Bot only outputs damage to one target at a time, moves to next after current is defeated."},
		[8] = {"dps aoe","AOE DPS","Bot uses AOE skills when there are multiple enemies in combat."},
		[9] = {"dps assist","DPS Assist","Bot assists in damaging enemies in the party."},
		[10] = {"dps debuff","Damage Debuff","Bot applies damage-over-time debuffs to targets in combat."},
		[11] = {"heal","Heal Teammates","Bot heals injured teammates in combat, no longer performs DPS output."},
		[12] = {"aoe","Group Attack","Bot uses group damage skills in combat."},
		[13] = {"flee","Maintain Distance","Bot attempts to run away when current target gets too close in combat."},
		[14] = {"fire","Fire Spells","Bot uses fire spells to output damage to targets in combat. (For Mage bots)"},
		[15] = {"fire aoe","Fire AOE","Bot uses fire AOE spells when there are multiple enemies in combat. (For Mage bots)"},
		[16] = {"frost","Frost Spells","Bot uses frost spells to output damage to targets in combat. (For Mage bots)"},
		[17] = {"frost aoe","Frost AOE","Bot uses frost AOE spells when there are multiple enemies in combat. (For Mage bots)"},
		[18] = {"arcane","Arcane Spells","Bot uses arcane spells to output damage to targets in combat. (For Mage bots)"},
		[19] = {"threat","Threat Control","Bot conservatively outputs damage in combat to prevent pulling aggro."},
		[20] = {"conserve mana","Energy Control","Bot conserves mana usage in combat, reducing output capability."},
		[21] = {"shadow","Shadow Spells","Bot uses shadow spells to output damage to targets in combat. (For Warlock and Priest bots)"},
		[22] = {"shadow aoe","Shadow AOE","Bot uses shadow AOE spells when there are multiple enemies in combat. (For Warlock and Priest bots)"},
		[23] = {"shadow debuff","Shadow Damage Debuff","Bot applies shadow damage-over-time debuffs to targets in combat. (For Warlock and Priest bots)"},
		[24] = {"melee","Melee Combat","Bot always stays close to targets for attacks in combat. (For Shaman bots)"},
		[25] = {"melee aoe","Melee Group Attack","Bot stays close to targets for group attacks in combat. (For Shaman bots)"},
		[26] = {"rshadow","Shadow Resistance Aura","Bot activates shadow resistance aura in combat. (For Paladin bots)"},
		[27] = {"rfrost","Frost Resistance Aura","Bot activates frost resistance aura in combat. (For Paladin bots)"},
		[28] = {"rfire","Fire Resistance Aura","Bot activates fire resistance aura in combat. (For Paladin bots)"},
		[29] = {"barmor","Armor Defense Aura","Bot activates armor defense aura in combat. (For Paladin bots)"},
		[30] = {"bspeed","Mount Speed Aura","Bot activates mount speed aura in combat. (For Paladin bots)"},
		[31] = {"rnature","Nature Resistance Aura","Bot activates nature resistance aura in combat. (For Hunter bots)"},
		[32] = {"bhealth","Health Buff","Bot applies health increasing buffs to self and teammates in combat."},
		[33] = {"bmana","Supportive Buff","Bot applies supportive buffs to self and teammates in combat."},
		[34] = {"bdps","Offensive Buff","Bot applies offensive buffs to self and teammates in combat."},
		[35] = {"bear","Bear and Dire Bear Form","Bot transforms into bear for DPS output in combat. (For Druid bots)"},
		[36] = {"cat","Cat Form","Bot transforms into cat for DPS output in combat. (For Druid bots)"},
		[37] = {"cat aoe","Cat Group Attack","Bot transforms into cat for group output in combat. (For Druid bots)"},
		[38] = {"caster","Ranged Spell Output","Bot uses ranged spells for output in combat. (For Druid and Shaman bots)"},
		[39] = {"caster aoe","Ranged Group Spells","Bot uses ranged AOE spells when there are multiple enemies in combat. (For Druid and Shaman bots)"},
		[40] = {"caster debuff","Ranged Damage Debuff","Bot applies ranged damage-over-time debuffs to targets in combat. (For Druid and Shaman bots)"},
		[41] = {"totems","Totems","Bot places totems nearby in combat. (For Shaman bots)"},
		[42] = {"loot","Looting","Bot loots nearby corpse drops in combat."},
		[43] = {"naxx","Naxxramas","Bot behavior targets Naxxramas dungeon. (Only effective in Naxxramas dungeon)"},
	};

	ClassStrategyNC = {
		[1] = {"grind","Autonomous Activity","Bot searches for targets within sight and attacks when not in combat."},
		[2] = {"move random","Random Movement","Bot moves randomly when bored out of combat."},
		[3] = {"attack weak","Free Attack","Bot freely selects targets to attack when entering combat out of combat."},
		[4] = {"attack force","Passive Attack","Bot does not perform any attacks out of combat, requires manual target assignment."},
		[5] = {"bhealth","Health Buff","Bot applies health increasing buffs to self and teammates out of combat."},
		[6] = {"bmana","Supportive Buff","Bot applies supportive buffs to self and teammates out of combat."},
		[7] = {"bdps","Offensive Buff","Bot applies offensive buffs to self and teammates out of combat."},
		[8] = {"emote","Emotes","Bot performs random emote actions when bored out of combat."},
		[9] = {"food","Rest","After leaving combat, bot drinks water and eats bread as needed."},
		[10] = {"loot","Looting","After leaving combat, bot loots nearby corpse drops."},
		[11] = {"stay","Stay","Bot stands still in place when not in combat."},
		[12] = {"follow","Follow","Bot follows player movement when not in combat."},
		[13] = {"quest","Questing","Bot accepts and completes quests with NPCs the player is interacting with when not in combat."},
		[14] = {"naxx","Naxxramas","Bot behavior targets Naxxramas dungeon. (Only effective in Naxxramas dungeon)"},
	};
end